version: "3"
services:
  web:
    build: .
    container_name: fastapi
    ports:
      - "5000:80"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./servers_data:/app/servers_data
    command: >
      bash -c "uvicorn server:app --host=0.0.0.0 --port=80"