version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - DEBUG=0
    depends_on:
      - db
    command: >
      bash -c "id && ls -la && whoami &&
             python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn -b 0.0.0.0:8000 project.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
      - "${NGINX_EXTERNAL_PORT_SSL}:443"
volumes:
  static_volume:
  media_volume: